[project]
name = "db_flights"
version = "0.0.1"
authors = [{ name = "tkocza" }]
description = "Metadata-driven ETL pipeline built with Databricks Asset Bundles and PySpark"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    # Any dependencies for jobs and pipelines in this project can be added here
    # See also https://docs.databricks.com/dev-tools/bundles/library-dependencies
    #
    # LIMITATION: for pipelines, dependencies are cached during development;
    # add dependencies to the 'environment' section of your pipeline.yml file instead
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=15.4,<15.5",
    "ipykernel",
]


# [project.scripts]
# main = "db_flights.main:main"

[project.scripts]
# entry points

# bronze
bronze_kaggle = "db_flights.bronze.bronze_kaggle:main"

# silver
silver_airlines = "db_flights.silver.airlines:main"
silver_airports = "db_flights.silver.airports:main"
silver_flights = "db_flights.silver.flights:main"

# gold
gold_dim_airlines = "db_flights.gold.dim_airlines:main"
gold_dim_airports = "db_flights.gold.dim_airports:main"
gold_fct_flights = "db_flights.gold.fct_flights:main"

# gold init
init_dim_time = "db_flights.init_gold.dim_time:main"
init_dim_airlines = "db_flights.init_gold.dim_airlines:main"
init_dim_airports = "db_flights.init_gold.dim_airports:main"
init_fct_flights = "db_flights.init_gold.fct_flights:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
