from pyspark.sql import SparkSession

'''
DDL is executed via spark.sql() to keep the public portfolio environment-independent
and avoid hardcoding a workspace-specific warehouse ID.
'''

spark = SparkSession.builder.getOrCreate()

def create_table_gold_dim_airlines():
    spark.sql("""
    CREATE TABLE IF NOT EXISTS db_flights.gold.dim_airlines (
        airline_id BIGINT GENERATED BY DEFAULT AS IDENTITY
            COMMENT 'Surrogate key for the airlines dimension',

        airline_code STRING NOT NULL
            COMMENT "Airline IATA code (2-letter)",

        airline STRING
            COMMENT "Full airline name",

        row_hash STRING
            COMMENT 'Hash of business attributes used for SCD2 change detection',

        valid_from TIMESTAMP
            COMMENT 'Timestamp from which this dimension version is valid',

        valid_to TIMESTAMP
            COMMENT 'Timestamp until which this dimension version is valid',

        is_current BOOLEAN
            COMMENT 'Indicates whether this is the current version of the record',
        
        CONSTRAINT pk_dim_airlines PRIMARY KEY (airline_id)
    )
    USING DELTA
    """)

def insert_special_records():
    spark.sql("""
            INSERT INTO db_flights.gold.dim_airlines (
                airline_id,
                airline_code,
                airline,
                row_hash,
                valid_from,
                valid_to,
                is_current
            )
            SELECT *
            FROM VALUES
                (
                    -1,
                    'UNKNOWN',
                    'Unknown Airline',
                    'NA',
                    NULL,
                    NULL,
                    TRUE
                ),
                (
                    -999,
                    'QUARANTINED',
                    'Missing Airline',
                    'NA',
                    NULL,
                    NULL,
                    TRUE
                )
            AS source(
                airline_id,
                airline_code,
                airline,
                row_hash,
                valid_from,
                valid_to,
                is_current
            )
            WHERE NOT EXISTS (
                SELECT 1
                FROM db_flights.gold.dim_airlines AS target
                WHERE target.airline_id = source.airline_id
            );
    """)

def main():
    create_table_gold_dim_airlines()
    insert_special_records()


if __name__ == "__main__":
    main()