from pyspark.sql import SparkSession

'''
DDL is executed via spark.sql() to keep the public portfolio environment-independent
and avoid hardcoding a workspace-specific warehouse ID.
'''

spark = SparkSession.builder.getOrCreate()

def create_table_gold_dim_airports():
    spark.sql("""
    CREATE TABLE IF NOT EXISTS db_flights.gold.dim_airports (
        airport_id BIGINT GENERATED BY DEFAULT AS IDENTITY
            COMMENT 'Surrogate key for the airport dimension',

        airport_code STRING NOT NULL
            COMMENT 'Unique airport IATA code (3-letter)',

        airport STRING
            COMMENT 'Full airport name',

        city STRING
            COMMENT 'City of airport location',

        state STRING
            COMMENT 'State or region',

        country STRING
            COMMENT 'Country',

        latitude DOUBLE
            COMMENT 'Latitude coordinate',

        longitude DOUBLE
            COMMENT 'Longitude coordinate',

        row_hash STRING
            COMMENT 'Hash of business attributes used for SCD2 change detection',

        valid_from TIMESTAMP
            COMMENT 'Timestamp from which this dimension version is valid',

        valid_to TIMESTAMP
            COMMENT 'Timestamp until which this dimension version is valid',

        is_current BOOLEAN
            COMMENT 'Indicates whether this is the current version of the record',
            
        CONSTRAINT pk_dim_airports PRIMARY KEY (airport_id)
    )
    USING DELTA;
    """)

def insert_special_records():
    spark.sql("""
        INSERT INTO db_flights.gold.dim_airports (
            airport_id,
            airport_code,
            airport,
            city,
            state,
            country,
            latitude,
            longitude,
            row_hash,
            valid_from,
            valid_to,
            is_current
        )
        SELECT *
        FROM (
            SELECT
                -1 AS airport_id,
                'UNKNOWN' AS airport_code,
                'Unknown Airport' AS airport,
                'Unknown' AS city,
                'Unknown' AS state,
                'Unknown' AS country,
                NULL AS latitude,
                NULL AS longitude,
                'NA' AS row_hash,
                NULL AS valid_from,
                NULL AS valid_to,
                TRUE AS is_current

            UNION ALL

            SELECT
                -999,
                'QUARANTINED',
                'Missing Airport',
                'Unknown',
                'Unknown',
                'Unknown',
                NULL,
                NULL,
                'NA',
                NULL,
                NULL,
                TRUE
        ) AS source
        WHERE NOT EXISTS (
            SELECT 1
            FROM db_flights.gold.dim_airports AS target
            WHERE target.airport_id = source.airport_id
        );
    """)


def main():
    create_table_gold_dim_airports()
    insert_special_records()


if __name__ == "__main__":
    main()